config/routes.rb
Snippets::Application.routes.draw do

  resources :snippet_tags

  resources :tags

  resources :snippets do
    resources :comments
  end

  get "snippets/create"

  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout

  match '/upvote/:snippet', :controller => "votes",
                            :action => "upvote",
                            :via => [:post],
                            :as => :upvote

  match '/downvote/:snippet', :controller => "votes",
                             :action => "downvote",
                             :via => [:post],
                             :as => :downvote

  match '/search', :controller => "snippet_tags",
                   :action => "search",
                   :via => [:get],
                   :as => :search

  match "/new" => "snippets#index"
  match "/top" => "snippets#top"

  root :to => 'snippets#index'

end

app/models/snippet_tag.rb
class SnippetTag < ActiveRecord::Base
  belongs_to :tag
  belongs_to :snippet

  attr_accessible :tag, :snippet

  validates :tag, :snippet, :presence => true
  validates :tag_id, :uniqueness => { :scope => :snippet_id }
end

app/controllers/snippet_tags_controller.rb
class SnippetTagsController < ApplicationController
  # GET /snippet_tags
  # GET /snippet_tags.json
  def index
    @snippet_tags = SnippetTag.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @snippet_tags }
    end
  end

  # GET /snippet_tags/1
  # GET /snippet_tags/1.json
  def show
    @snippet_tag = SnippetTag.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @snippet_tag }
    end
  end

  # GET /snippet_tags/new
  # GET /snippet_tags/new.json
  def new
    @snippet_tag = SnippetTag.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @snippet_tag }
    end
  end

  # GET /snippet_tags/1/edit
  def edit
    @snippet_tag = SnippetTag.find(params[:id])
  end

  # POST /snippet_tags
  # POST /snippet_tags.json
  def create
    @snippet_tag = SnippetTag.new(params[:snippet_tag])

    respond_to do |format|
      if @snippet_tag.save
        format.html { redirect_to @snippet_tag, notice: 'snippet_tag was successfully created.' }
        format.json { render json: @snippet_tag, status: :created, location: @snippet_tag }
      else
        format.html { render action: "new" }
        format.json { render json: @snippet_tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /snippet_tags/1
  # PUT /snippet_tags/1.json
  def update
    @snippet_tag = SnippetTag.find(params[:id])

    respond_to do |format|
      if @snippet_tag.update_attributes(params[:snippet_tag])
        format.html { redirect_to @snippet_tag, notice: 'snippet_tag was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @snippet_tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /snippet_tags/1
  # DELETE /snippet_tags/1.json
  def destroy
    @snippet_tag = SnippetTag.find(params[:id])
    @snippet_tag.destroy

    respond_to do |format|
      format.html { redirect_to snippet_tags_url }
      format.json { head :no_content }
    end
  end

  QUERY_PATTERN = /\A(?<tags>(\[(\w|\-)+\])+)?\s*(?<therest>.*)\Z/
  TAG_PATTERN   = /\A\s*\[/

  def search
    query = params[:q]
    if QUERY_PATTERN =~ query
      tag_portion = $~[:tags]
      the_rest    = $~[:therest]

      @snippets = nil

      if not tag_portion.blank?
        @snippets = search_tags(tag_portion)

        if not the_rest.blank?
          @snippets = search_rest(the_rest, @snippets)
        end
      elsif not the_rest.blank?
        @snippets = search_rest(the_rest)
      end

      respond_to do |format|
        format.html
        format.json { head :no_content }
      end
    else
      raise ArgumentError.new
    end
  end

  private
  def search_tags (tag_portion)
    # cleanup
    tag_portion = tag_portion.sub(/\A\s*\[/, '')
    tag_portion = tag_portion.sub(/\]\s*\Z/, '')

    tags = tag_portion.split(/\]\s*\[/)

    results = SnippetTag.select(:snippet_id)
                        .joins(:tag)
                        .where("tags.tag IN (?)", tags.join(","))
                        .group(:snippet_id)
                        .having("COUNT(DISTINCT(tags.id)) = ?", tags.size)

    results.map { |st| Snippet.find(st.snippet_id) }
  end

  def search_rest (the_rest, filtered_snippets = nil)
    terms = the_rest.split(/\s+/)

    if filtered_snippets.nil?
      return Snippet.all.select do |s|
        desc = s.description
        for t in terms
          return false unless desc.include? t
        end
        true
      end

    else
      return filtered_snippets.select do |s|
        desc = s.description
        for t in terms
          return false unless desc.include? t
        end
        true
      end
    end
  end
end

app/views/snippet_tags/_form.html.haml
= form_for @snippet_tag do |f|
  - if @snippet_tag.errors.any?
    #error_explanation
      %h2= "#{pluralize(@snippet_tag.errors.count, "error")} prohibited this snippet tag from being saved:"
      %ul
        - @snippet_tag.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :tag
    = f.text_field :tag
  .field
    = f.label :snippet
    = f.text_field :snippet
  .actions
    = f.submit 'Save'

app/views/snippet_tags/edit.html.haml
%h1 Editing snippet_tag

= render 'form'

= link_to 'Show', @snippet_tag
\|
= link_to 'Back', snippet_tags_path

app/views/snippet_tags/index.html.haml
%h1 Listing snippet_tags

%table
  %tr
    %th Tag
    %th Snippet
    %th
    %th
    %th

  - @snippet_tags.each do |snippet_tag|
    %tr
      %td= snippet_tag.tag
      %td= snippet_tag.snippet
      %td= link_to 'Show', snippet_tag
      %td= link_to 'Edit', edit_snippet_tag_path(snippet_tag)
      %td= link_to 'Destroy', snippet_tag, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New snippet tag', new_snippet_tag_path

app/views/snippet_tags/new.html.haml
%h1 New Snippet Tag

= render 'form'

= link_to 'Back', snippet_tags_path

app/views/snippet_tags/search.html.haml
%h1 Search results

= render "snippets/snippet_list"

app/views/snippet_tags/show.html.haml
%p#notice= notice

%p
  %b Tag:
  = @snippet_tag.tag
%p
  %b Snippet:
  = @snippet_tag.snippet

= link_to 'Edit', edit_snippet_tag_path(@snippet_tag)
\|
= link_to 'Back', snippet_tags_path