config/routes.rb
Snippets::Application.routes.draw do

  resources :snippet_tags

  resources :tags

  resources :snippets do
    resources :comments
  end

  get "snippets/create"

  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout

  match '/upvote/:snippet', :controller => "votes",
                            :action => "upvote",
                            :via => [:post],
                            :as => :upvote

  match '/downvote/:snippet', :controller => "votes",
                             :action => "downvote",
                             :via => [:post],
                             :as => :downvote

  match '/search', :controller => "snippet_tags",
                   :action => "search",
                   :via => [:get],
                   :as => :search

  match "/new" => "snippets#index"
  match "/top" => "snippets#top"

  root :to => 'snippets#index'

end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
  belongs_to :user

  attr_accessible :code, :points, :title, :description, :user_id, :snippet_id, :all_tags
  has_many :comments
  has_many :tags
  has_many :snippet_tags

  validates :user, :code, :title, :description, :presence => true

  after_create :setup_snippet

  def setup_snippet
    self.points = 0
    self.user.upvote_or_remove(self)
  end

  def increment_points (incr = 1)
    self.update_attributes(:points => self.points + incr)
  end

  def decrement_points (decr = 1)
    self.update_attributes(:points => self.points - decr)
  end

  def all_tags=(tag_input)
    tags = tag_input.split(/\s*\,\s*/)
    valid_tag = /[a-zA-Z0-9_\+\-\']+/
    tags.each do |tag_name|
      # validate each tag, and reject if they're not all (\w|-)+
      if (valid_tag =~ tag_name)
        tag_name.downcase!
        tag = Tag.find_or_create_by_tag(tag_name)
        SnippetTag.create(:tag => tag, :snippet => self)
      end
    end
  end

  def all_tags
    snippet_tags = SnippetTag.where(:snippet_id => self.id)
    tags = snippet_tags.map { |st| Tag.find(st.tag_id) }

    tags
  end
end

app/controllers/snippet_controller.rb
class SnippetController < ApplicationController
  def home
  end

  def create
  end
end

app/controllers/snippets_controller.rb
require 'date'

class SnippetsController < ApplicationController
  # GET /snippets
  # GET /snippets.json
  def index
    @snippets = Kaminari.paginate_array(Snippet.order("created_at DESC")).page(params[:page]).per(10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @snippets }
    end
  end

  # GET /top
  # GET /top.json
  def top
    time_span = params[:t]
    now = Time.now.utc
    # possible of t = {"all", "day", "month", "year"}
    # if t is not in that set, then return today ("day")

    @snippets = Snippet.order("points DESC")

    case time_span
    when "day"
      lower_bound = now - 1.day
    when "month"
      lower_bound = now - 1.month
    when "year"
      lower_bound = now - 1.year
    when "all"
      lower_bound = nil
    else    # defaults to "day"
      lower_bound = now - 1.day
    end

    @snippets = @snippets.where("created_at >= ?", lower_bound) unless lower_bound.nil?
    @snippets = Kaminari.paginate_array(@snippets.all).page(params[:page]).per(10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @snippets }
    end
  end

  # GET /snippets/1
  # GET /snippets/1.json
  def show
    @snippet = Snippet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @snippet }
    end
  end

  # GET /snippets/new
  # GET /snippets/new.json
  
  def new
    @snippet = Snippet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @snippet }
    end
  end

  # POST /snippets
  # POST /snippets.json
  def create
    tags = params[:tags]
    @snippet = Snippet.new(params[:snippet])
    @snippet.all_tags = tags

    respond_to do |format|
      if @snippet.save
        format.html { redirect_to @snippet, notice: 'Snippet was successfully created.' }
        format.json { render json: @snippet, status: :created, location: @snippet }
      else
        format.html { render action: "new" }
        format.json { render json: @snippet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /snippets/1
  # PUT /snippets/1.json
  def update
    @snippet = Snippet.find(params[:id])

    respond_to do |format|
      if @snippet.update_attributes(params[:snippet])
        format.html { redirect_to @snippet, notice: 'Snippet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @snippet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /snippets/1
  # DELETE /snippets/1.json
  def destroy
    @snippet = Snippet.find(params[:id])
    @snippet.destroy

    respond_to do |format|
      format.html { redirect_to snippets_url }
      format.json { head :no_content }
    end
  end
  
end

app/helpers/snippets_helper.rb
module SnippetsHelper
end

app/views/snippets/_box.html.erb
<div class="out">
	<div class="topA">
		<%= link_to image_tag('uparrow.png'), upvote_path(snippet), method: :post %>
	</div>
	<div class="points">
		<%= snippet.points %>
	</div>
	<div class="btmA">
		<%= link_to image_tag('downarrow.png'), downvote_path(snippet), method: :post %>
	</div>
	<div class="greenbox">
		<div class="title">
			<h2><%= link_to snippet.title, snippet_path(snippet)%></h2>
			</div>
			<div id=>
			<%= snippet.user.name %>
		</div>
        <div class="code"><%= simple_format(snippet.code) %></div>
		<%= truncate(snippet.description, :length => 80) %><br/>
		<div class="time">
		<%= "created " + localize_time(snippet.created_at) + " ago" %>
		</div>
		<div class="dest">
		<% if snippet.user==current_user%>
		<%= link_to 'Destroy', snippet, method: :delete, data: { confirm: 'Are you sure?' } %>
		<% end%>
		</div>
        <p>
          <strong>Tags:</strong>
          <% @snippet.all_tags.map {|t| t.tag }.each do |tag| %>
            <%= link_to tag, URI.escape("/search?q=[#{tag}]") %>
          <% end %>
        </p>
	</div>
</div>

app/views/snippets/_form.html.erb
<%= form_for(@snippet) do |f| %>
<% if @snippet.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@snippet.errors.count, "error") %> prohibited this snippet from being saved:</h2>

	<ul>
		<% @snippet.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
  <% end %>

<div class='formed'>
<div class="field">
	<%= f.label :title %>
	<br />
	<%= f.text_field :title %>
</div>
<div class="field">
	<%= f.label :description %>
	<br />
	<%= f.text_field :description %>
</div>
<div class="field" id="coded">
	<%= f.label :code %>
	<br />
	<%= f.text_area :code%>
	<br />
</div>
<button type="button" onClick="clicked()">
	Pick
</button>

<div id="result"></div>
<input type="button" value="Get selection" onmousedown="getSelText()">
	<%= f.hidden_field :user_id, :value => current_user.id %>
  <div class="field" id="tags">
    <label for="tags">Tags</label>
    <input id="tags" name="tags" size="30" type="text">
  </div>
	<div class="actions">
		<%= f.submit %>
	</div>
	<% end %>
	</div>

app/views/snippets/_snippet_list.html.erb
<% if @snippets.nil? || @snippets.blank? %>
  <p>There's nothing here</p>
<% else %>
  <% @snippets.each do |snippet| %>
    <%= render :partial => "snippets/box", :locals => { :snippet => snippet } %>
  <% end %>
<% end %>

app/views/snippets/index.html.erb
<%= render :partial => "snippets/snippet_list" %>


<%= paginate @snippets %>

app/views/snippets/new.html.erb
<div id="ftitle"><p>Create Snippit</p></div>

<% if current_user %>
  <%= render 'form' %>
<% else %>
  <%= link_to "Log in with Facebook", "/auth/facebook" %>
<% end %>

<%= link_to 'Back', snippets_path %>

app/views/snippets/show.html.erb
<p id="notice"><%= notice %></p>

<%= render :partial => "snippets/box", :locals => { :snippet => @snippet } %>

<ol class="comments">
    <% @snippet.comments.reverse.each do |comment| %>
    <% if !comment.content.nil? %>
    <li>
      <% commenter = comment.commenter %>
      <%-#= link_to commenter.name, commenter %>
      <p><%= comment.content %></p>
      <f class="timestamp <%= 'own' if current_user?(commenter) %>"><%= time_ago_in_words(comment.created_at) %> ago, by <%= commenter.name %></f>

      <% if current_user?(commenter) %>
        <%= link_to "x", [@snippet, comment], :method => :delete, :confirm => "You sure?", :title => "Delete this comment", :class => "delete" %>
      <% end %>
    </li>
    <% end %>
    <% end %>

    <li>
      <%= form_for([@snippet, @snippet.comments.build(:user_id => current_user.id, :snippet_id => @snippet.id)]) do |f| %>
        <%= f.text_field :content, :placeholder => "Type your comment here..." %>
        <%= f.submit "Comment", :class => "btn small default" %>
      <% end %>
    </li>
</ol>


<%= link_to 'Back', snippets_path %>

app/views/snippets/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @snippet.title

%p
  %b Code:
  = @snippet.code

.vote-container{:data => {:snippet_id => @snippet.id}}
  = better_button_to "Up", upvote_path(@snippet), {:method => :post, :class => "up-form"}, {:class => "up-arrow"}
  %p.points= @snippet.points
  = better_button_to "Down", downvote_path(@snippet), {:method => :post, :class => "down-form"}, {:class => "down-arrow"}

app/views/snippets/top.html.erb
<div id="topbar">

	<ul>
		<li id="top">
		Top snippets:
		</li>
		<li>
			<%= link_to "Today", "#{top_path}?t=day" %>
		</li>
		<li>
			<%= link_to "Month", "#{top_path}?t=month" %>
		</li>
		<li>
			<%= link_to "Year", "#{top_path}?t=year" %>
		</li>
		<li>
			<%= link_to "All time", "#{top_path}?t=all" %>
		</li>
	</ul>
</div>
<%= render :partial => "snippets/snippet_list" %>


<%= paginate @snippets %>