config/routes.rb
Snippets::Application.routes.draw do

  resources :snippet_tags

  resources :tags

  resources :snippets do
    resources :comments
  end

  get "snippets/create"

  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout

  match '/upvote/:snippet', :controller => "votes",
                            :action => "upvote",
                            :via => [:post],
                            :as => :upvote

  match '/downvote/:snippet', :controller => "votes",
                             :action => "downvote",
                             :via => [:post],
                             :as => :downvote

  match '/search', :controller => "snippet_tags",
                   :action => "search",
                   :via => [:get],
                   :as => :search

  match "/new" => "snippets#index"
  match "/top" => "snippets#top"

  root :to => 'snippets#index'

end

app/views/layouts/_search.html.erb
<form action=<%= search_path %> method="get">
	<input type='text', name='q'>
	<input type='submit', value='Search'>
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Snippets</title>
		<link rel="stylesheet" type="text/css" href="app/assets/stylesheets/application.css">

		<%= stylesheet_link_tag "application" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
	</head>
	<body>

		<div id="topLn" class="navbar">
			<% if current_user %>
			<div class="fb">
				<p>
					signed in as: <%= current_user.name %>
				</p>
				<div id="but" class='nice'}>
					<%= button_to "signout", signout_path,{:class => "btn btn-success"} %>
				</div>
			</div>
			<% else %>
			<div class="fb1">
				<%= link_to "Log in with Facebook", "/auth/facebook" %>
			</div>
			<% end %>
		</div>
		<div id="btmLn" class="navbar">
			<div id="logo">
				<%= image_tag 'snippit.png'%>
			</div>
			<div id="bar">
				<%= image_tag 'navbar.png' %>
			</div>
			<div id="recent">
				<%= link_to image_tag('recent.png'), snippets_path%>
				<div id="popular">
					<%= link_to image_tag('popular.png'), top_path%>
				</div>
				<div id="create">
					<%= link_to image_tag('submit.png'), new_snippet_path %>
				</div>
				<div id="search">
					<%= render :partial => "layouts/search" %>
				</div>
			</div>
		</div>
		</div>
		<div id="content">
			<%= yield %>
			<script src="http://api.filepicker.io/v0/filepicker.js"></script>
			<script type="text/javascript">
				//Seting up Filepicker.io with your api key
				filepicker.setKey('AK3SHdPbbQYqb7Q1GeoIhz');
				function clicked() {
					filepicker.getFile('text/*',{'services' :[filepicker.SERVICES.COMPUTER,filepicker.SERVICES.GITHUB,filepicker.SERVICES.DROPBOX,filepicker.SERVICES.GOOGLE_DRIVE]},
					function(url, metadata){
						filepicker.getContents(url, function(data){
							var txt = document.createTextNode(data);
							var link = document.getElementById("result").appendChild(txt);
						});
					});
				};
				function getSelText(){
				    var txt = '';
				     if (window.getSelection){
				        txt = window.getSelection();
				             }
				    else if (document.getSelection){
				        txt = document.getSelection();
				            }
				    else if (document.selection){
				        txt = document.selection.createRange().text;
				            }
				    else return;
				document.getElementsByName("snippet[code]")[0].value =  txt;
				};
			</script>
		</div>
	</body>
</html>